CREATE DATABASE DB_SHOPPING_COMPANY
USE DB_SHOPPING_COMPANY;
----------------CREATE TABLES------------------
CREATE TABLE CUSTOMER(CUSTOMER_ID INT PRIMARY KEY IDENTITY,FIRST_NAME NVARCHAR(50),LAST_NAME NVARCHAR(50),CUSTOMER_EMAIL NVARCHAR(50),GENDER VARCHAR(10),MOBILE_NO VARCHAR(20))
-----------------------------
CREATE TABLE CUSTOMER_ADDRESS(ADD_ID INT,ADDRESS1 VARCHAR(100),STATE VARCHAR(20),
CITY VARCHAR(20),CUTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID));
-----------------------
CREATE TABLE DB_ERRORS(ERROR_ID INT IDENTITY,USER_NAME VARCHAR(50),ERROR_NUMBER INT,ERROR_STATE INT,ERROR_SEVERITY INT,
ERROR_LINE INT,ERROR_PROCEDURE VARCHAR(50),ERROR_MESSAGE VARCHAR(50),ERROR_DATETIME DATETIME);
-----------CREATE PROCEDURE FOR CUSTOMER TABLE------------
ALTER PROCEDURE ADD_CUSTOMER @CUSTOMER_ID INT, @FIRST_NAME VARCHAR(20), @LAST_NAME VARCHAR(20),
@CUSTOMER_EMAIL VARCHAR(50),@GENDER VARCHAR(10),@MOBILE_NO VARCHAR(20)
AS
  BEGIN TRY
	INSERT INTO CUSTOMER SELECT @CUSTOMER_ID,@FIRST_NAME,@LAST_NAME,@CUSTOMER_EMAIL,@GENDER,@MOBILE_NO
  END TRY
  BEGIN CATCH
  ----------------INSERT RECORD IN ERROR TABLE WHEN EXCEPTION OCCUR---------------
	INSERT INTO DB_ERRORS VALUES(SUSER_NAME(),ERROR_NUMBER(),ERROR_STATE(),ERROR_SEVERITY(),
	ERROR_LINE(),ERROR_PROCEDURE(),ERROR_MESSAGE(),GETDATE());
  END CATCH
  ----------------INSERT RECORD IN CUSTOMER TABLE------------
  EXEC ADD_CUSTOMER 5,'SACHIN','GARG','SACHIN123@GMAIL.COM','MALE',9808814961
    --------------CREATE CUSTOMER ADDRESS PROCEDURE----------
  CREATE PROC ADD_CUSTOMER_ADDRESS @ADD_ID INT,@ADDRESS1 VARCHAR(MAX),@STATE VARCHAR(20),@CITY VARCHAR(20),@CUSTOMER_ID INT
  AS
  BEGIN TRY
	INSERT INTO CUSTOMER_ADDRESS SELECT @ADD_ID,@ADDRESS1,@STATE,@CITY,@CUSTOMER_ID
  END TRY
  BEGIN CATCH
	INSERT INTO DB_ERRORS VALUES(SUSER_NAME(),ERROR_NUMBER(),ERROR_STATE(),ERROR_SEVERITY(),
	ERROR_LINE(),ERROR_PROCEDURE(),ERROR_MESSAGE(),GETDATE())
  END CATCH
    -----------INSERT RECORD IN CUSTOMER_ADDRESS_TABLE------------
  EXEC ADD_CUSTOMER_ADDRESS 4,'50,RAJPURA,NADIM','U.P.','AGRA',4
  EXEC ADD_CUSTOMER_ADDRESS 5,'51,RAJPURA,NADIM','U.P.','AGRA',5

SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER_ADDRESS;
SELECT * FROM DB_ERRORS;
--------------------BASIC PRACTICE OF EXCEPTION HANDLING----------------
BEGIN TRY
SELECT 10/0 ERROR
END TRY
BEGIN CATCH
SELECT
ERROR_NUMBER() AS ERROR_NO,
ERROR_LINE() AS ERROR_LINENO,
ERROR_MESSAGE() AS ERROR_MSSG,
ERROR_PROCEDURE() AS ERROR_PROC,
ERROR_SEVERITY() AS ERROR_SEVER,
ERROR_STATE() AS ERROR_STAT;
END CATCH;


